rule preprocess_batch:
    input:
        script = "../atlassing_rectum_submit.sh"
    output: 
        "/lustre/scratch126/humgen/projects/sc-eqtl-ibd/analysis/bradley_analysis/results/rectum/healthy/All_not_gt_subset/objects/adata_PCAd_scvid.h5ad"
    conda:
        "sc4"
    params: 
       o = "../logs/rectum_atlassing01-%J-output.log",
       e = "../logs/rectum_atlassing01-%J-error.log",
       q = "long",
       J = "rectum_atlassing01"
    shell:
        """
        bsub -o {params.o} -e {params.e} -q {params.q} -J {params.J} < {input.script}
        """

rule umap_param_sweep:
    input: 
        "/lustre/scratch126/humgen/projects/sc-eqtl-ibd/analysis/bradley_analysis/results/rectum/healthy/All_not_gt_subset/objects/adata_PCAd_scvid.h5ad",
        script = "../param_sweep_submit.sh"
    conda:
        "sc4"
    params:
        o = "../logs/param_sweep-%J-output.log",
        e = "../logs/param_sweep-%J-error.log",
        q = "long",
        J = "param_sweep"
    output:
        "/lustre/scratch126/humgen/projects/sc-eqtl-ibd/analysis/bradley_analysis/results/rectum/healthy/All_not_gt_subset/figures/embedding_param_sweep/umap500nn_2_min_dist_3_spread.pdf"
    shell:
        """
        conda activate sc4
        bsub -o {params.o} -e {params.e} -q {params.q} -J {params.J} < {input.script}
        """


        