discard_other_inflams: yes 
all_blood_immune: "yes"
min_nUMI: 300
use_absolute_nUMI: "yes"
use_relative_mad: "yes"
lineage_column: "sum_majority_lineage"
relative_grouping: "tissue|sum_majority_lineage"
relative_nMAD_threshold: 2.5
relative_nUMI_log: "yes"
min_nGene: 100
use_absolute_nGene: "yes"
relative_nGene_log: "yes"
MT_thresh_gut: 50
MT_thresh_blood: 20
use_absolute_MT: "yes"
absolute_max_MT: 50
min_mean_nCount_per_samp_blood: 3000
min_mean_nCount_per_samp_gut: 5000
min_mean_nGene_per_samp_blood: 1000
min_mean_nGene_per_samp_gut: 750
use_abs_per_samp: "yes"
filt_blood_keras: "no"
n_variable_genes: 4000
remove_problem_genes: "yes"