configfile: "config.yaml"
print(config)

rule qc_raw:
    input:
        "input_test/adata_raw_input_{tissue}.h5ad"
    output:
        "results/{tissue}/objects/adata_PCAd.h5ad",
        "results/{tissue}/objects/adata_PCAd_batched.h5ad",
        "results/{tissue}/tables/knee.txt"
    params:
        discard_other_inflams=config["discard_other_inflams"], 
        all_blood_immune=config["all_blood_immune"],
        min_nUMI=config["min_nUMI"],
        use_absolute_nUMI=config["use_absolute_nUMI"],
        use_relative_mad=config["use_relative_mad"],
        lineage_column=config["lineage_column"],
        relative_grouping=config["relative_grouping"],
        relative_nMAD_threshold=config["relative_nMAD_threshold"],
        relative_nUMI_log=config["relative_nUMI_log"],
        min_nGene=config["min_nGene"],
        use_absolute_nGene=config["use_absolute_nGene"],
        relative_nGene_log=config["relative_nGene_log"],
        MT_thresh_gut=config["MT_thresh_gut"],
        MT_thresh_blood=config["MT_thresh_blood"],
        use_absolute_MT=config["use_absolute_MT"],
        absolute_max_MT=config["absolute_max_MT"],
        min_mean_nCount_per_samp_blood=config["min_mean_nCount_per_samp_blood"],
        min_mean_nCount_per_samp_gut=config["min_mean_nCount_per_samp_gut"],
        min_mean_nGene_per_samp_blood=config["min_mean_nGene_per_samp_blood"],
        min_mean_nGene_per_samp_gut=config["min_mean_nGene_per_samp_gut"],
        use_abs_per_samp=config["use_abs_per_samp"],
        filt_blood_keras=config["filt_blood_keras"],
        n_variable_genes=config["n_variable_genes"],
        remove_problem_genes=config["remove_problem_genes"],
        batch_correction=config["batch_correction"],
        benchmark_batch_correction=config["benchmark_batch_correction"]
    resources:
        mem=10000,
        queue='normal',
        mem_mb=10000,
        mem_mib=10000,
        disk_mb=10000,
        tmpdir="tmp"
    conda:
        "scvi-env"
    shell:
        r"""
        python  bin/001_raw_QC_sm.py \
        --input_file {input} \
        --tissue {wildcards.tissue} \
        --discard_other_inflams {params.discard_other_inflams} \
        --all_blood_immune {params.all_blood_immune} \
        --min_nUMI {params.min_nUMI} \
        --use_absolute_nUMI {params.use_absolute_nUMI} \
        --use_relative_mad {params.use_relative_mad} \
        --lineage_column {params.lineage_column} \
        --relative_grouping {params.relative_grouping} --relative_nMAD_threshold {params.relative_nMAD_threshold} \
        --relative_nUMI_log {params.relative_nUMI_log} \
        --min_nGene {params.min_nGene} \
        --use_absolute_nGene {params.use_absolute_nGene} \
        --relative_nGene_log {params.relative_nGene_log} \
        --MT_thresh_gut {params.MT_thresh_gut} \
        --MT_thresh_blood {params.MT_thresh_blood} \
        --use_absolute_MT {params.use_absolute_MT} \
        --absolute_max_MT {params.absolute_max_MT} \
        --min_mean_nCount_per_samp_blood {params.min_mean_nCount_per_samp_blood} \
        --min_mean_nCount_per_samp_gut {params.min_mean_nCount_per_samp_gut} \
        --min_mean_nGene_per_samp_blood {params.min_mean_nGene_per_samp_blood} \
        --min_mean_nGene_per_samp_gut {params.min_mean_nGene_per_samp_gut} \
        --use_abs_per_samp {params.use_abs_per_samp} \
        --filt_blood_keras {params.filt_blood_keras} \
        --n_variable_genes {params.n_variable_genes} \
        --remove_problem_genes {params.remove_problem_genes} \
        --batch_correction {params.batch_correction} \
        --benchmark_batch_correction {params.benchmark_batch_correction}
        """
  
rule get_nn:
    input:
        "results/{tissue}/objects/adata_PCAd.h5ad",
        "results/{tissue}/tables/knee.txt"
    output:
        "results/{tissue}/tables/optimum_nn.txt"
    params:
        use_matrix="X_pca"
    resources:
        mem=10000,
        queue='long',
        mem_mb=10000,
        mem_mib=10000,
        disk_mb=10000,
        tmpdir="tmp"
    conda:
        "bbknn"
    shell:
        r"""
        python bin/002_bbknn.py \
            --tissue {wildcards.tissue} \
            --fpath {input[0]} \
            --knee_file {input[1]} \
            --use_matrix {params.use_matrix}
        """


rule get_umap:
    input:
        "results/{tissue}/objects/adata_PCAd_batched.h5ad",
        "results/{tissue}/tables/knee.txt",
        "results/{tissue}/tables/optimum_nn.txt"
    output:
        "results/{tissue}/objects/adata_PCAd_batched_umap.h5ad"
    params:
        use_matrix="X_pca_harmony,X_pca",
        col_by="experiment_id,tissue,sum_majority_lineage,category__machine,label__machine"
    resources:
        mem=10000,
        queue='long',
        mem_mb=10000,
        mem_mib=10000,
        disk_mb=10000,
        tmpdir="tmp"
    conda:
        "scvi-env"
    shell:
        r"""
        python bin/003_umap_embedding.py \
            --tissue {wildcards.tissue} \
            --fpath {input[0]} \
            --knee_file {input[1]} \
            --use_matrix {params.use_matrix} \
            --optimum_nn_file {input[2]} \
            --col_by {params.col_by}
        """

# Define clustering resolutions
clustering_resolutions = list(config["clustering_resolutions"])
print(clustering_resolutions)

rule cluster_array:
    input:
        "results/{tissue}/objects/adata_PCAd_batched_umap.h5ad"
    output:
        "results/{tissue}/tables/clustering_array/leiden_{clustering_resolution}.csv"
    params:
        pref_matrix=config["pref_matrix"]
    resources:
        mem=10000,
        queue='normal',
        mem_mb=10000,
        mem_mib=10000,
        disk_mb=10000,
        tmpdir="tmp"
    conda:
        "scvi-env"
    shell:
        r"""
        mkdir -p results/{wildcards.tissue}/tables/clustering_array
        python bin/004_scanpy_cluster.py \
            --tissue {wildcards.tissue} \
            --fpath {input[0]} \
            --pref_matrix {params.pref_matrix} \
            --clustering_resolution {wildcards.clustering_resolution}
        """

#rule add_megagut:
#    input:
#        "results/{tissue}/objects/adata_PCAd_batched_umap.h5ad"
#    output:
#        "results/{tissue}/tables/annotation/CellTypist/celltypist_megagut.csv",
#        "results/{tissue}/figures/UMAP/CellTypist/umap_CellTypist_megagut.csv"
#    resources:
#        mem=10000,
#        queue='normal',
#        mem_mb=10000,
#        mem_mib=10000,
#        disk_mb=10000,
#        tmpdir="tmp"
#    conda:
#        "scvi-env"
#    shell:
#        r"""
#        mkdir -p results/{wildcards.tissue}/tables/annotation
#        mkdir -p results/{wildcards.tissue}/tables/annotation/CellTypist
#        results/{tissue}/figures/UMAP/CellTypist
#        python 
#        """

rule test_clusters:
    input:
        "results/{tissue}/tables/clustering_array/leiden_{clustering_resolution}.csv" 
    output:
        "results/{tissue}/tables/clustering_array/leiden_{clustering_resolution}_MCC.csv" 
    params:
    resources:
        mem=10000,
        queue='normal',
        mem_mb=10000,
        mem_mib=10000,
        disk_mb=10000,
        tmpdir="tmp"
    shell:
        r"""
        module load ISG/singularity/3.9.0
        singularity exec -B /lustre -B /software /software/hgi/containers/yascp/yascp.cog.sanger.ac.uk-public-singularity_images-wtsihgi_nf_scrna_qc_6bb6af5-2021-12-23-3270149cf265.sif bin/999-test_keras.py \
            --tissue {wildcards.tissue}
        """

# Define the rule all to specify the target file(s)
rule all:
    input:
        "results/blood/objects/adata_PCAd_batched_umap.h5ad"
