# Decide tissue (s)
tissue: 
- 'combined' # This is what the pipeline will be ran on. Refers to the output of Snakefile_cluster_within_lineage-002

# QC parameters
discard_other_inflams: "no" # Remove non CD inflammtation samples
all_blood_immune: "no" # Treat all the blood data as immune if using?
min_nUMI: 500 # Minimum nUMI
use_absolute_nUMI: "yes" # Use the min UMI cut off?
use_relative_mad: "no" # Use a relative MAD threshold
lineage_column: "sum_majority_lineage" # Which coloumn to use as lineage annotation
relative_grouping: "sum_majority_lineage" # For mad computation, what is the grouping we want to use? seperate by "," if >1, e.g "tissue,sum_majority_lineage"
relative_nMAD_threshold: 2.5 # Threshold of nMad
filter_sequentially: "no" # Define and filter the data sequentially?
nMad_directionality: "bi" # Can be bi|uni. unidirectional medians cells only removed for nMads above or below the median. bidirectional medians cells removed for nMads exceeding threshold in either direction
plot_within: "yes" # A list of values to plot QC metrics within, seperated by ",". E.g, if "lineage,category" plots will be made witihn each of these. If "None", will be plotted in none
relative_nUMI_log: "yes" # Use relative nUMI
min_nGene: 250 # Min nGene
use_absolute_nGene: "yes" # Use min nGene
relative_nGene_log: "yes" # Also use a relative nGene?
MT_thresh_gut: 50 # MT thresh for gut samples (rectum + TI)
MT_thresh_blood: 20 # MT thresh for blood
use_absolute_MT: "yes" # Use ansolute MT
min_MT: 0 # Minmum MT% - epithelial cells with 0 (!) seem to be seperating in the embedding. If don't want to apply this, set to 0
absolute_max_MT: 50 # In this case, the absolute threshold is only used if the relatve thresholds exceed it
use_MT_thresh_blood_gut_immune: "no" # Use the absolute MT threshold for blood on the gut immune cells? 
min_median_nCount_per_samp_blood: 0 # Exclude samples with median nCount lower than this value (blood). Samples with low medians for these metrics tend to integrate badly. If want to ignor this, set to very high number, e.g 60k
min_median_nCount_per_samp_gut: 0 # Same but gut
min_median_nGene_per_samp_blood: 1000 # Exclude samples with median nGene than this value (blood)
min_median_nGene_per_samp_gut: 1000 # Same but gut
max_ncells_per_sample: 18000 # Maximum number of cells that can originate from a single sample. If don't want to use these, set to ridiculously high number like 1000000
min_ncells_per_sample: 0 # Minimum number of cells that can originate from a single sample. If don't want to use, set to 0
use_abs_per_samp: "yes" # Use these absolute metrics
filt_cells_pre_samples: "yes" # Filter the cells based on the above metrics BEFORE filtering the samples. NOTE: This will drastically alter the distirbution of QC metrics and therefore sample choice
filt_blood_keras: "no" # Filter blood for keras probability? Some cells annotated as non-immune
n_variable_genes: 5000 # Number of variable genes for PCA calculation
remove_problem_genes: "yes" # Remover MT/RP/IG genes from the highly variable genes?
per_samp_relative_threshold: "no" # Do you want to apply sample-level QC based on relative threshold? If so, the above value of relative_nMAD_threshold and directionality will be used
sample_level_grouping: "disease_tissue" # How do you want to group samples? E.g within "tissue" or "disease_tissue"
cols_sample_relative_filter: "nCells" # Which cols to carry out the relative filtering on at the sample level? Can be any of ['nCells', 'Median_nCounts', 'Median_nGene_by_counts', 'Median_MT'], or the same preceded by 'log10_'. These should be seperated by ",", e.g "Median_nCounts,Median_nGene_by_counts"
# NOTE: per-sample level thresholds are currently computed with samples excluded by hard thresholds kept in. I.e hard thresholds are currently not applied BEFORE the relative thresholds

# Batch correction options
batch_column: "samp_tissue"
batch_correction_methods: ["scVI", "scVI_default", "scANVI"] # List of batch correction methods to test, max = ["scVI", "scVI_default", "scANVI", "Harmony"]
correct_variable_only: True # Compute embedding on variable genes only?
scANVI_annot_column: "sum_majority_lineage"
benchmark_batch_correction: False # Whether to benchmark the batch effect correction using scib-metrics
var_explained_cols: "samp_tissue,sum_majority_lineage,category__machine,label__machine,log10_total_counts,total_counts_nMAD,log10_n_genes_by_counts,n_genes_by_counts_nMAD,MT_perc_nMads,total_counts_gene_group__ribo_rna,log1p_total_counts_gene_group__ribo_rna,pct_counts_gene_group__mito_transcript,tissue" # ONe string, seperated by ","

# If not performing benchmarking, then select the preferred matrix
pref_matrix: "scVI" # Can leave empty if benching

# Determine whether to get optimum NN from bbknn? # If false, will use number of nearest neighbours decided a priori
use_bbknn: True
nn_choice: "Manual" # Can be 'Manual' to use pre-defined NN parameter provided by 'nn' parameter, 'bbknn' to use the nn selected by bbknn or 'array' to run an array test over 'nn_values' parameter 
nn_values: [15, 30, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
nn: 30

# What to plot on the initial UMAP post clustering? Check these w/ respect to embedding
col_by: "experiment_id,tissue,sum_majority_lineage,category__machine,label__machine,sum_Immune,sum_Epithelial,sum_Mesenchymal,log10_total_counts,total_counts_nMAD,log10_n_genes_by_counts,n_genes_by_counts_nMAD,MT_perc_nMads,total_counts_gene_group__ribo_rna,log1p_total_counts_gene_group__ribo_rna,pct_counts_gene_group__mito_transcript,manual_lineage,leiden,EPCAM,KRT8,KRT18,CDH5,COL1A1,COL1A2,COL6A2,VWF,PTPRC,CD3D,CD3G,CD3E,CD79A,CD79B,CD14,FCGR3A,CD68,CD83,CSF1R,FCER1G"

# Otherwise, what are the keras hyperparameters to use? Currently: these are from Leland and not neccessarily optimised for use on the different datasets together or independently
# Don't use quotes around these
activation: softmax
loss: categorical_crossentropy
optimizer: sgd
sparsity_l1__activity: 0.01
sparsity_l1__kernel: 0.0001
sparsity_l1__bias: 0.0001
sparsity_l2__activity: 0.0001
sparsity_l2__kernel: 0.01
sparsity_l2__bias: 0.01

# Original all data file
original_input_round1: "/lustre/scratch126/humgen/projects/sc-eqtl-ibd/analysis/bradley_analysis/scripts/scRNAseq/Atlassing/tissues_combined/input_v7/adata_raw_input_all.h5ad" # Change this file to alter what the very first input file was for the ENTIRE analysis

# Do the two step prediction? E.g one for lineage, one for subclusters
two_step_prediction: True # Are we doing the prediction in two steps? I.e - will each cell be streamed by the lineage model into each of the subsequent models. If False, each cell will undergo the lineage model, and then all other subsequent model and results recombined
round1_model: "results_round2/combined/tables/lineage_model/base.h5" # Absolute path to the model that determines cell lineage. Generated by "make_lineage_prediction_model" rule in Snakefile_cluster_within_lineage-002
round1_model_weights: "results_round2/combined/tables/lineage_model/base-weights.tsv.gz" # Absolute path to the model weights that determine cell lineage. Generated by "make_lineage_prediction_model" rule in Snakefile_cluster_within_lineage-002
round2_prefix: "all_" # What was the prefix of the round 2 analysis? This will be added to the values found within the the round1 col to sort so that the optim resolution, and therefore models, can be found. E.g if the value "epithelial" is in the first model, but the output from round2 looks like "results/all_epithelial", then this value should be "all_"
round1_groups:
- "epithelial"
- "immune"
- "mesenchymal"

# Celltypist options:
add_celltypist: True # Should the script run to get the celltypist megagut annotations for these cells? 
celltypist_model: "/lustre/scratch127/cellgen/cellgeni/cakirb/celltypist_models/megagut_celltypist_lowerGI+lym_adult_mar24.pkl" # Can be multiple, seperated by ","
celltypist_model_name: "Megagut_adult_lower_GI_mar24" # Name to add to cols. Corresponding to above models

# Threshold for subset of predicted cell-type annotations from keras:
probability_threshold: 0.5 # Threshold at which to filter the anndata object after addition of probabilities for all cell types. If no filtration required, set this to 0
