# Bradley August 2024
tissue: combined
subset: manual_lineage
subset_value: 
- Epithelial
- T
- B
- Myeloid
- Mesenchymal
input: results_round2/combined/objects/adata_grouped_post_cluster_QC.h5ad
cluster_column: leiden
method: wilcoxon
filter: "True"
min_in_group_fraction: 0.5
max_out_group_fraction: 0.3
min_fold_change: 1.5
baseout: results_round2
compare_annots: Celltypist:megagut_celltypist_lowerGI+lym_adult_mar24:predicted_labels,Azimuth:predicted.celltype.l1,Azimuth:predicted.celltype.l2,Azimuth:predicted.celltype.l3,Celltypist:cluster-ti-cd_healthy-freeze005_clustered_final:predicted_labels
external_marker_sets: external_markers/helmsley_23.txt
external_marker_set_names: helmsley_23" 