# Decide tissue (s)
tissue: 
- 'all_Epithelial'
- 'all_Mesenchymal'
- 'all_T'
- 'all_Myeloid'
- 'all_B'

# Original h5
base_tissue_original_h5: "/lustre/scratch126/humgen/projects/sc-eqtl-ibd/analysis/bradley_analysis/scripts/scRNAseq/Atlassing/tissues_combined/input_v7/adata_raw_input_all.h5ad" # Output file from the first round of analysis

# QC parameters
discard_other_inflams: "no" # Remove non CD inflammtation samples
all_blood_immune: "no" # Treat all the blood data as immune if using?
min_nUMI: 500 # Minimum nUMI
relative_grouping: "tissue" # For mad computation, what is the grouping we want to use? seperate by "," if >1, e.g "tissue,sum_majority_lineage"
relative_nMAD_threshold: 3 # Threshold of nMad
relative_nMAD_threshold_epithelial: 2 # Threshold for nMad (epithelial)
nMad_directionality: "bi" # Can be bi|uni. unidirectional medians cells only removed for nMads above or below the median. bidirectional medians cells removed for nMads exceeding threshold in either direction
threshold_method: "outer" # Whether to use relative thresholds and in which direction. Can be "specific" to be specific to the relative_grouping, "outer" to apply the outer window of the relative groupings, or None to not apply at all.  
min_nGene: 250 # Min nGene
MT_thresh_gut: 50 # MT thresh for gut samples (rectum + TI)
MT_thresh_blood: 20 # MT thresh for blood
use_MT_thresh_blood_gut_immune: "no" # Use the absolute MT threshold for blood on the gut immune cells? 
min_median_nCount_per_samp_blood: 0 # Exclude samples with median nCount lower than this value (blood). Samples with low medians for these metrics tend to integrate badly. If want to ignor this, set to very high number, e.g 60k
min_median_nCount_per_samp_gut: 0 # Same but gut
min_median_nGene_per_samp_epi: 2000 # Exclude samples with median nGene than this value (epithelium)
min_median_nGene_per_samp_nonepi: 0 # Same but not epithelium
max_ncells_per_sample: 100000 # Maximum number of preQC cells that can originate from a single sample
min_ncells_per_sample: 10 # Minimum number of cells that can originate from a single sample. If don't want to use, set to 0
plot_per_samp_qc: "yes" # Plot the distribution of QC parameters across samples (e.g within tissue) - Takes up LOTS of memory if lots of samples
use_abs_per_samp: "yes" # Use these absolute metrics
filt_blood_keras: "no" # Filter blood for keras probability? Some cells annotated as non-immune
filt_cells_pre_samples: "yes" # Filter the cells based on the above metrics BEFORE filtering the samples. NOTE: This will drastically alter the distirbution of QC metrics and therefore sample choice
n_variable_genes: 5000 # Number of variable genes for PCA calculation
hvgs_within: "samp_tissue" # How to calculate HVGs? If don't want to use, set to None
remove_problem_genes: "yes" # Remover MT/RP/IG genes from the highly variable genes?
per_samp_relative_threshold: "no" # Do you want to apply sample-level QC based on relative threshold? If so, the above value of relative_nMAD_threshold and directionality will be used
sample_level_grouping: "disease_tissue" # How do you want to group samples? E.g within "tissue" or "disease_tissue"
cols_sample_relative_filter: "nCells" # Which cols to carry out the relative filtering on at the sample level? Can be any of ['nCells', 'Median_nCounts', 'Median_nGene_by_counts', 'Median_MT'], or the same preceded by 'log10_'. These should be seperated by ",", e.g "Median_nCounts,Median_nGene_by_counts"
calc_hvgs_together: "no"
# NOTE: per-sample level thresholds are currently computed with samples excluded by hard thresholds kept in. I.e hard thresholds are currently not applied BEFORE the relative thresholds


# Batch correction options
batch_column: "samp_tissue"
batch_correction_methods: ["scVI", "scVI_default", "scANVI"] # List of batch correction methods to test, max = ["scVI", "scVI_default", "scANVI", "Harmony"]
correct_variable_only: True # Compute embedding on variable genes only?
scANVI_annot_column: "sum_majority_lineage"
benchmark_batch_correction: False # Whether to benchmark the batch effect correction using scib-metrics
var_explained_cols: "samp_tissue,sum_majority_lineage,category__machine,label__machine,log10_total_counts,total_counts_nMAD,log10_n_genes_by_counts,n_genes_by_counts_nMAD,MT_perc_nMads,total_counts_gene_group__ribo_rna,log1p_total_counts_gene_group__ribo_rna,pct_counts_gene_group__mito_transcript,tissue,manual_lineage,Celltypist:megagut_celltypist_lowerGI+lym_adult_mar24:predicted_labels,Celltypist:megagut_celltypist_lowerGI+lym_adult_mar24:majority_voting,Celltypist:megagut_celltypist_lowerGI+lym_adult_mar24:conf_score" # ONe string, seperated by ","

# If not performing benchmarking, then select the preferred matrix
pref_matrix: "scVI" # Can leave empty if benching

# Determine whether to get optimum NN from bbknn? # If false, will use number of nearest neighbours decided a priori
use_bbknn: True
nn_choice: "Manual" # Can be 'Manual' to use pre-defined NN parameter provided by 'nn' parameter, 'bbknn' to use the nn selected by bbknn or 'array' to run an array test over 'nn_values' parameter 
nn_values: [15, 30, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
nn: 30
nn_epithelial: 50

# What to plot on the initial UMAP post clustering? Check these w/ respect to embedding
col_by: "experiment_id,tissue,sum_majority_lineage,category__machine,label__machine,sum_Immune,sum_Epithelial,sum_Mesenchymal,log10_total_counts,total_counts_nMAD,log10_n_genes_by_counts,n_genes_by_counts_nMAD,MT_perc_nMads,total_counts_gene_group__ribo_rna,log1p_total_counts_gene_group__ribo_rna,pct_counts_gene_group__mito_transcript,EPCAM,KRT8,KRT18,CDH5,COL1A1,COL1A2,COL6A2,VWF,PTPRC,CD3D,CD3G,CD3E,CD79A,CD79B,CD14,FCGR3A,CD68,CD83,CSF1R,FCER1G"

# Optimise run parameters?
optimise_run_params: False
keras_optimisation_res: 3.0 # Resolution at which keras should be optimised

# Otherwise, what are the keras hyperparameters to use? Currently: these are from Leland and not neccessarily optimised for use on the different datasets together or independently
# Don't use quotes around these
activation: softmax
loss: categorical_crossentropy
optimizer: sgd
sparsity_l1__activity: 0.01
sparsity_l1__kernel: 0.0001
sparsity_l1__bias: 0.0001
sparsity_l2__activity: 0.0001
sparsity_l2__kernel: 0.01
sparsity_l2__bias: 0.01

# Clustering and validation options
clustering_resolutions: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5] # What are the range of clustering resolutions to iterate over? [0.1, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
MCC_thresh: 0.75 # What is the threshold of Matthews correlation coefficient at which all clusters are deemed reproducible? The optimum cluster resolution that will be taken forward will be the greatest at which MCC of all clusters exceeds this value

# Cluster-level QC and post-clustering sample QC
max_proportion: 0.2 # Maximum proportion of a cluster coming from a single sample? 0.2=20%
min_ncells: 0 # Minimum number of cells contributing to a single cluster? 
# Post sample-level filtration
filter_based_on_prev_fails: True # Filter clusters based on whether the cells were uniquely failing in lower resolutions? 
consistent_failing_cluster_proportion: 0.8 # Contribution of a failing cluster in a given resolution to failing clusterrs at a lower resoluton
num_consistent_failing_clusters: 1 # Maximum number of failing clusters to query lower resolutions for?
use_cluster_QC: False # Do we actually want to use the cluster QC? If not, will just take the max resolution for all cells passing MCC_thresh
remove_blacklist: "no" # When re-embedding, and merging the anndata across lineages, should we remove the blacklist samples from those contributing heavily to single cluster FROM ALL SAMPLES

# Original combined file
combined_file: "results_round1/all/objects/adata_manual_lineage_clean.h5ad" # Absolute file name (no wildcards) for the file which includes lineages combined

# Celltypist options:
add_celltypist: True # Should the script run to get the celltypist megagut annotations for these cells? 
celltypist_model: "/lustre/scratch127/cellgen/cellgeni/cakirb/celltypist_models/megagut_celltypist_lowerGI+lym_adult_mar24.pkl" # Can be multiple, seperated by ","
celltypist_model_name: "Megagut_adult_lower_GI_mar24" # Name to add to cols. Corresponding to above models

# Threshold for subset of predicted cell-type annotations from keras:
probability_threshold: 0.5 # Threshold at which to filter the anndata object after addition of probabilities for all cell types. If no filtration required, set this to 0