# Decide tissue (s)
tissue: 
- 'combined' # This is what the pipeline will be ran on. Refers to the output of Snakefile_cluster_within_lineage-002

# Decide method. Most important choice! All other options relate only to keras
method: "CellTypist"
celltypist_model: "results_round3/combined/objects/leiden-adata_grouped_post_cluster_QC.pkl" # Onlly used if celltypist is being used

# What are the keras hyperparameters to use? Currently: these are from Leland and not neccessarily optimised for use on the different datasets together or independently
# Don't use quotes around these
activation: softmax
loss: categorical_crossentropy
optimizer: sgd
sparsity_l1__activity: 0.01
sparsity_l1__kernel: 0.0001
sparsity_l1__bias: 0.0001
sparsity_l2__activity: 0.0001
sparsity_l2__kernel: 0.01
sparsity_l2__bias: 0.01

# Original all data file
original_input_round1: "/lustre/scratch126/humgen/projects/sc-eqtl-ibd/analysis/bradley_analysis/scripts/scRNAseq/Atlassing/input_v7/adata_raw_input_all.h5ad" # Change this file to alter what the very first input file was for the ENTIRE analysis

# Do the two step prediction? E.g one for lineage, one for subclusters
two_step_prediction: True # Are we doing the prediction in two steps? 
round1_model: "results_round3/combined/tables/lineage_model/base.h5" # Absolute path to the model that determines cell lineage. Generated by "make_lineage_prediction_model" rule in Snakefile_cluster_within_lineage-002
round1_model_weights: "results_round3/combined/tables/lineage_model/base-weights.tsv.gz" # Absolute path to the model weights that determine cell lineage. Generated by "make_lineage_prediction_model" rule in Snakefile_cluster_within_lineage-002
round2_prefix: "all_" # What was the prefix of the round 2 analysis? This will be added to the values found within the the round1 col to sort so that the optim resolution, and therefore models, can be found. E.g if the value "epithelial" is in the first model, but the output from round2 looks like "results/all_epithelial", then this value should be "all_"
round1_groups:
- "epithelial"
- "immune"
- "mesenchymal"

# List of samples (for cell prediction within samples) - This will have been generated by the third round
samp_list: "results_round3/combined/tables/sample_list.txt" # Full: "results_round3/combined/tables/sample_list.txt"